export interface GoogleFontDef {
  family: string
  category: "serif" | "sans-serif" | "display" | "monospace" | "handwriting"
  weights: number[]
}

export const GOOGLE_FONTS: GoogleFontDef[] = [
  { family: "Inter", category: "sans-serif", weights: [400, 500, 600, 700] },
  { family: "Roboto", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Open Sans", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Lato", category: "sans-serif", weights: [400, 700] },
  { family: "Poppins", category: "sans-serif", weights: [400, 500, 600, 700] },
  { family: "Montserrat", category: "sans-serif", weights: [400, 500, 600, 700] },
  { family: "Nunito", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Nunito Sans", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Work Sans", category: "sans-serif", weights: [400, 500, 600] },
  { family: "Raleway", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Rubik", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Karla", category: "sans-serif", weights: [400, 700] },
  { family: "Mulish", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Manrope", category: "sans-serif", weights: [400, 500, 700] },
  { family: "DM Sans", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Barlow", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Josefin Sans", category: "sans-serif", weights: [400, 600] },
  { family: "Quicksand", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Heebo", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Source Sans 3", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Playfair Display", category: "serif", weights: [400, 600, 700] },
  { family: "Merriweather", category: "serif", weights: [400, 700] },
  { family: "Lora", category: "serif", weights: [400, 500, 600] },
  { family: "PT Serif", category: "serif", weights: [400, 700] },
  { family: "Noto Serif", category: "serif", weights: [400, 700] },
  { family: "Crimson Text", category: "serif", weights: [400, 600] },
  { family: "Libre Baskerville", category: "serif", weights: [400, 700] },
  { family: "Cormorant Garamond", category: "serif", weights: [400, 600] },
  { family: "EB Garamond", category: "serif", weights: [400, 600] },
  { family: "Bitter", category: "serif", weights: [400, 600, 700] },
  { family: "Spectral", category: "serif", weights: [400, 600] },
  { family: "Frank Ruhl Libre", category: "serif", weights: [400, 700] },
  { family: "Cardo", category: "serif", weights: [400, 700] },
  { family: "Domine", category: "serif", weights: [400, 700] },
  { family: "Oswald", category: "display", weights: [400, 500, 700] },
  { family: "Bebas Neue", category: "display", weights: [400] },
  { family: "Anton", category: "display", weights: [400] },
  { family: "Abril Fatface", category: "display", weights: [400] },
  { family: "Archivo Black", category: "display", weights: [400] },
  { family: "Righteous", category: "display", weights: [400] },
  { family: "Pacifico", category: "handwriting", weights: [400] },
  { family: "Dancing Script", category: "handwriting", weights: [400, 700] },
  { family: "Caveat", category: "handwriting", weights: [400, 700] },
  { family: "Sacramento", category: "handwriting", weights: [400] },
  { family: "Great Vibes", category: "handwriting", weights: [400] },
  { family: "Satisfy", category: "handwriting", weights: [400] },
  { family: "JetBrains Mono", category: "monospace", weights: [400, 700] },
  { family: "Roboto Mono", category: "monospace", weights: [400, 700] },
  { family: "Source Code Pro", category: "monospace", weights: [400, 700] },
  { family: "IBM Plex Mono", category: "monospace", weights: [400, 700] },
  { family: "Space Mono", category: "monospace", weights: [400, 700] },
  { family: "IBM Plex Sans", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Fira Sans", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Assistant", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Cabin", category: "sans-serif", weights: [400, 500, 700] },
  { family: "Titillium Web", category: "sans-serif", weights: [400, 600, 700] },
  { family: "Zilla Slab", category: "serif", weights: [400, 600, 700] },
  { family: "Alegreya", category: "serif", weights: [400, 700] },
  { family: "Arvo", category: "serif", weights: [400, 700] },
  { family: "Vollkorn", category: "serif", weights: [400, 600] },
]

export function findGoogleFont(family: string): GoogleFontDef | undefined {
  return GOOGLE_FONTS.find((f) => f.family === family)
}
