import { boolean, index, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core"

/**
 * Auth schema.
 *
 * The `user`, `session`, `account`, and `verification` tables match the shape
 * Better Auth expects (text ids generated by the library, camelCase fields
 * mapped to snake_case columns). Keep these in sync with the Better Auth CLI
 * (`bunx @better-auth/cli generate`) when upgrading.
 */

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({ byUser: index("session_user_id_idx").on(t.userId) }),
)

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Provider identity: providerId is "credential" | "google" | "apple";
    // accountId is the provider's user id (or the user id for credentials).
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    // OAuth tokens (null for the credential provider).
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    // Hashed password, only set for the "credential" provider.
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    byUser: index("account_user_id_idx").on(t.userId),
    providerIdentity: uniqueIndex("account_provider_identity_idx").on(t.providerId, t.accountId),
  }),
)

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    // e.g. an email for verification / password reset / OTP.
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({ byIdentifier: index("verification_identifier_idx").on(t.identifier) }),
)

/**
 * Application schema.
 *
 * A resume is owned by a user; the full ResumeData object lives in `data`
 * (jsonb) so the flexible block/theme structure needs no rigid columns.
 */
export const resume = pgTable(
  "resume",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("Untitled"),
    data: jsonb("data").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  // One resume per user (for now): a unique index enforces the invariant and
  // enables an atomic upsert keyed on userId.
  (t) => ({ byUser: uniqueIndex("resume_user_id_unique").on(t.userId) }),
)

export type User = typeof user.$inferSelect
export type Account = typeof account.$inferSelect
export type Session = typeof session.$inferSelect
export type Resume = typeof resume.$inferSelect
export type NewResume = typeof resume.$inferInsert
